"""
runtime/k8s_go_operator.py
==========================
Go operator binary packaging foundation (ADR-043).

Default-off. Renders a minimal Go operator module under
deploy/k8s/operator/go/, Fake-builds a stub artifact for CI, and soft-
invokes ``go build`` / ``docker build`` when gated. Not a shipped
production operator binary.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Mapping, Optional

from runtime.nats_supercluster import _truthy


class GoOperatorError(RuntimeError):
    """Go operator packaging failed."""


def go_available() -> bool:
    return bool(shutil.which("go"))


def docker_available() -> bool:
    return bool(shutil.which("docker"))


GO_MAIN_STUB = '''\
// Code generated by KerrOS ADR-043 foundation — not a production operator.
package main

import (
        "fmt"
        "os"
)

func main() {
        fmt.Fprintln(os.Stderr, "kerros-nats-operator foundation stub — wire controller-runtime when funded")
        os.Exit(0)
}
'''

GO_MOD_STUB = """module github.com/kerros/nats-operator

go 1.22
"""

DOCKERFILE_STUB = """\
# ADR-043 foundation Dockerfile — not a published image
FROM golang:1.22-alpine AS build
WORKDIR /src
COPY . .
RUN go build -o /out/kerros-nats-operator .

FROM alpine:3.20
COPY --from=build /out/kerros-nats-operator /usr/local/bin/kerros-nats-operator
ENTRYPOINT ["kerros-nats-operator"]
"""

MAKEFILE_STUB = """\
# ADR-043 foundation Makefile
BINARY ?= kerros-nats-operator
.PHONY: build image
build:
\tgo build -o bin/$(BINARY) .
image:
\tdocker build -t kerros/nats-operator:dev .
"""


@dataclass
class GoOperatorConfig:
    enabled: bool = False
    module_path: str = "github.com/kerros/nats-operator"
    project_dir: str = "deploy/k8s/operator/go"
    binary_name: str = "kerros-nats-operator"
    image: str = "kerros/nats-operator:dev"
    allow_write: bool = False
    allow_build: bool = False
    allow_image: bool = False

    @classmethod
    def from_mapping(
        cls,
        raw: Optional[Mapping[str, Any]] = None,
        *,
        base: Optional[Path] = None,
    ) -> "GoOperatorConfig":
        data = dict(raw or {})
        enabled = data.get("enabled", False)
        env = os.environ.get("KERROS_ACTOR_MESH_GO_OPERATOR")
        if env is not None:
            enabled = _truthy(env)
        else:
            enabled = _truthy(enabled)

        module = os.environ.get("KERROS_ACTOR_MESH_GO_OPERATOR_MODULE")
        if module is None:
            module = str(data.get("module_path") or "github.com/kerros/nats-operator")

        project = os.environ.get("KERROS_ACTOR_MESH_GO_OPERATOR_DIR")
        if project is None:
            project = str(data.get("project_dir") or "deploy/k8s/operator/go")
        path = Path(project)
        if not path.is_absolute() and base is not None:
            path = Path(base) / path

        binary = os.environ.get("KERROS_ACTOR_MESH_GO_OPERATOR_BINARY")
        if binary is None:
            binary = str(data.get("binary_name") or "kerros-nats-operator")

        image = os.environ.get("KERROS_ACTOR_MESH_GO_OPERATOR_IMAGE")
        if image is None:
            image = str(data.get("image") or "kerros/nats-operator:dev")

        allow_write = data.get("allow_write", False)
        env_w = os.environ.get("KERROS_ACTOR_MESH_GO_OPERATOR_WRITE")
        if env_w is not None:
            allow_write = _truthy(env_w)
        else:
            allow_write = _truthy(allow_write)

        allow_build = data.get("allow_build", False)
        env_b = os.environ.get("KERROS_ACTOR_MESH_GO_OPERATOR_BUILD")
        if env_b is not None:
            allow_build = _truthy(env_b)
        else:
            allow_build = _truthy(allow_build)

        allow_image = data.get("allow_image", False)
        env_i = os.environ.get("KERROS_ACTOR_MESH_GO_OPERATOR_IMAGE_BUILD")
        if env_i is not None:
            allow_image = _truthy(env_i)
        else:
            allow_image = _truthy(allow_image)

        return cls(
            enabled=bool(enabled),
            module_path=str(module or "").strip() or "github.com/kerros/nats-operator",
            project_dir=str(path),
            binary_name=str(binary or "kerros-nats-operator").strip() or "kerros-nats-operator",
            image=str(image or "kerros/nats-operator:dev").strip(),
            allow_write=bool(allow_write),
            allow_build=bool(allow_build),
            allow_image=bool(allow_image),
        )


@dataclass
class GoOperatorPackager:
    """Render / Fake-build / soft go|docker build for NATS operator."""

    cfg: GoOperatorConfig
    _builds: int = 0
    _last: dict[str, Any] = field(default_factory=dict)
    _lock: threading.Lock = field(default_factory=threading.Lock)

    def preview(self) -> dict[str, Any]:
        return {
            "module_path": self.cfg.module_path,
            "binary_name": self.cfg.binary_name,
            "image": self.cfg.image,
            "project_dir": self.cfg.project_dir,
            "go": go_available(),
            "docker": docker_available(),
            "main_go": GO_MAIN_STUB,
            "go_mod": f"module {self.cfg.module_path}\n\ngo 1.22\n",
        }

    def write_sources(self) -> dict[str, Any]:
        if not self.cfg.enabled:
            raise GoOperatorError("Go operator packaging disabled")
        preview = self.preview()
        if not self.cfg.allow_write:
            return {
                "ok": False,
                "skipped": True,
                "error": "write disabled",
                "preview": {k: preview[k] for k in ("module_path", "binary_name", "image")},
            }
        root = Path(self.cfg.project_dir)
        root.mkdir(parents=True, exist_ok=True)
        written: list[str] = []
        main = root / "main.go"
        main.write_text(GO_MAIN_STUB, encoding="utf-8")
        written.append(str(main))
        gomod = root / "go.mod"
        gomod.write_text(f"module {self.cfg.module_path}\n\ngo 1.22\n", encoding="utf-8")
        written.append(str(gomod))
        docker = root / "Dockerfile"
        docker.write_text(DOCKERFILE_STUB, encoding="utf-8")
        written.append(str(docker))
        make = root / "Makefile"
        make.write_text(MAKEFILE_STUB, encoding="utf-8")
        written.append(str(make))
        readme = root / "README.md"
        readme.write_text(
            "# KerrOS Go NatsBroker operator (ADR-043)\n\n"
            "Foundation stub — not a shipped production binary.\n",
            encoding="utf-8",
        )
        written.append(str(readme))
        out = {"ok": True, "written": written, "at": time.time()}
        with self._lock:
            self._last = dict(out)
        return out

    def build(self) -> dict[str, Any]:
        if not self.cfg.enabled:
            raise GoOperatorError("Go operator packaging disabled")
        root = Path(self.cfg.project_dir)
        bin_dir = root / "bin"
        artifact = bin_dir / self.cfg.binary_name
        if not self.cfg.allow_build:
            # Fake build: write a stub artifact marker when write allowed
            if self.cfg.allow_write:
                bin_dir.mkdir(parents=True, exist_ok=True)
                artifact.write_text(
                    f"FAKE_BINARY {self.cfg.binary_name}\n", encoding="utf-8"
                )
            out = {
                "ok": True,
                "dry_run": True,
                "artifact": str(artifact) if self.cfg.allow_write else "",
                "go": go_available(),
                "note": "Fake build — set allow_build for soft go build",
            }
            with self._lock:
                self._builds += 1
                self._last = dict(out)
            return out
        if not go_available():
            raise GoOperatorError("go toolchain not installed")
        if not (root / "main.go").is_file():
            if self.cfg.allow_write:
                self.write_sources()
            else:
                raise GoOperatorError("sources missing; enable allow_write first")
        bin_dir.mkdir(parents=True, exist_ok=True)
        proc = subprocess.run(
            ["go", "build", "-o", str(artifact), "."],
            cwd=str(root),
            capture_output=True,
            timeout=120,
            check=False,
        )
        out = {
            "ok": proc.returncode == 0,
            "artifact": str(artifact),
            "returncode": proc.returncode,
            "stderr": proc.stderr.decode("utf-8", errors="replace")[:400],
            "at": time.time(),
        }
        with self._lock:
            self._builds += 1
            self._last = dict(out)
        return out

    def build_image(self) -> dict[str, Any]:
        if not self.cfg.enabled:
            raise GoOperatorError("Go operator packaging disabled")
        if not self.cfg.allow_image:
            return {
                "ok": True,
                "dry_run": True,
                "image": self.cfg.image,
                "docker": docker_available(),
                "note": "image build skipped — set allow_image",
            }
        if not docker_available():
            raise GoOperatorError("docker not installed")
        root = Path(self.cfg.project_dir)
        if not (root / "Dockerfile").is_file():
            if self.cfg.allow_write:
                self.write_sources()
            else:
                raise GoOperatorError("Dockerfile missing; enable allow_write first")
        proc = subprocess.run(
            ["docker", "build", "-t", self.cfg.image, "."],
            cwd=str(root),
            capture_output=True,
            timeout=300,
            check=False,
        )
        return {
            "ok": proc.returncode == 0,
            "image": self.cfg.image,
            "returncode": proc.returncode,
            "stderr": proc.stderr.decode("utf-8", errors="replace")[:400],
            "at": time.time(),
        }

    def stats(self) -> dict[str, Any]:
        with self._lock:
            return {
                "enabled": self.cfg.enabled,
                "module_path": self.cfg.module_path,
                "binary_name": self.cfg.binary_name,
                "image": self.cfg.image,
                "allow_write": self.cfg.allow_write,
                "allow_build": self.cfg.allow_build,
                "allow_image": self.cfg.allow_image,
                "go": go_available(),
                "docker": docker_available(),
                "builds": self._builds,
                "last": dict(self._last),
            }


def build_go_operator(
    cfg: Optional[Mapping[str, Any] | GoOperatorConfig] = None,
    *,
    base: Optional[Path] = None,
) -> Optional[GoOperatorPackager]:
    if isinstance(cfg, GoOperatorConfig):
        resolved = cfg
    else:
        resolved = GoOperatorConfig.from_mapping(cfg, base=base)
    if not resolved.enabled:
        return None
    return GoOperatorPackager(cfg=resolved)
