"""
agents.py — five specialized agents.

IMPORTANT: these are NOT autonomous actors. Each agent is just a
system-prompt + memory-scope wrapper around the same planner.py brain
(local Qwen first, OpenRouter fallback). Every agent's output goes
through propose_action() in assistant.py exactly like the daily
planner does — there is no separate, less-supervised path for these.

Adding an agent = adding an entry to AGENTS below. No other code
needs to change (this is the 'upgradable' pattern from the plugin
system, applied to agents instead of action executors).
"""
from planner import _call_local, _call_openrouter, load_preferences
import memory_store

AGENTS = {
    "cybersecurity": {
        "label": "Cybersecurity Agent",
        "role": (
            "You are a cybersecurity specialist. Review the given context for "
            "security risks, misconfigurations, or exposure. Cite the specific "
            "detail that concerns you. Never claim to have fixed or blocked "
            "anything — only report and suggest."
        ),
    },
    "data_analysis": {
        "label": "Data Analysis Agent",
        "role": (
            "You are a data analyst. Summarize patterns, trends, or anomalies "
            "in the given data. State your confidence level and what evidence "
            "backs each claim. Never present a guess as a fact."
        ),
    },
    "web_developer": {
        "label": "Web Developer Agent",
        "role": (
            "You are a web development specialist. Given a task or bug "
            "description, propose a concrete technical approach or code "
            "change. Note any assumptions you're making about the stack."
        ),
    },
    "app_developer": {
        "label": "App Developer Agent",
        "role": (
            "You are a mobile/app development specialist. Given a task, "
            "propose an implementation approach appropriate for "
            "resource-constrained environments. Note platform assumptions."
        ),
    },
    "machine_learning": {
        "label": "Machine Learning Agent",
        "role": (
            "You are a machine learning specialist. Given a task or dataset "
            "description, suggest a modeling approach and note its "
            "limitations honestly, including where it could fail."
        ),
    },
}


def run_agent(agent_name, task_description, extra_context=""):
    """
    Runs one specialized agent on a task. Returns
    (draft_text, reasoning, evidence, source) — same shape as
    planner.generate_plan(), so it plugs into the same approval flow.
    """
    if agent_name not in AGENTS:
        raise ValueError(f"Unknown agent: {agent_name}")

    agent = AGENTS[agent_name]
    preferences = load_preferences()

    # Read whatever this agent is scoped to see (read-only org knowledge,
    # plus any other agent memory explicitly granted in memory_store.SCOPES)
    conventions = memory_store.read_scoped(agent_name, "readonly", "conventions.md") or ""

    prompt = (
        f"{agent['role']}\n\n"
        f"House conventions (read-only context):\n{conventions}\n\n"
        f"User preferences: style={preferences.get('reply_style','concise')}\n\n"
        f"Task:\n{task_description}\n\n"
        f"{extra_context}\n"
        f"Remember: this is a DRAFT for human review only. "
        f"Do not claim any action has been taken."
    )

    draft = _call_local(prompt)
    source = "local (Qwen 0.5B / llama.cpp)"
    if not draft:
        draft = _call_openrouter(prompt)
        source = "cloud (OpenRouter)"
    if not draft:
        return None, None, None, None

    # Agent saves its own working notes to its own read/write folder —
    # never touches another agent's folder.
    memory_store.write_own(agent_name, "last_task.md", f"# Last task\n\n{task_description}\n\n## Draft\n{draft}")

    reasoning = f"Generated by {agent['label']} ({source})."
    evidence = f"Based on: task description provided, house conventions (readonly), model: {source}."
    return draft, reasoning, evidence, source
