"""
planner.py — the actual reasoning brain, swapped in for the old
rule-based suggest_daily_plan().

Priority: LOCAL (llama.cpp + Qwen 0.5B) first — private, free, works
offline. Falls back to OpenRouter only if local is unavailable/fails
or is explicitly disabled. This is the opposite priority order of
KerrOS's core/engine.py bug from earlier (that one tried cloud first
by mistake) — here local-first is deliberate and correct for a
privacy-sensitive personal task assistant.

Every call returns (draft_text, reasoning, evidence) — never executes
anything. The caller is always responsible for routing the result
through propose_action() in assistant.py.
"""
import os
import json
import subprocess
from pathlib import Path

try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parent / ".env")
except ImportError:
    pass

import requests

APP_DIR = Path(__file__).resolve().parent

# ── Config ────────────────────────────────────────────────────────
LLAMA_BIN = os.getenv("LLAMA_BIN", "")          # path to llama-simple-chat or similar
MODEL_PATH = os.getenv("MODEL_PATH", "")         # path to qwen0.5b .gguf
LOCAL_ENABLED = bool(LLAMA_BIN and MODEL_PATH and Path(LLAMA_BIN).exists() and Path(MODEL_PATH).exists())

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "")
OPENROUTER_MODEL = os.getenv("PLANNER_OPENROUTER_MODEL", "inclusionai/ling-3.0-flash:free")
MAX_TOKENS = int(os.getenv("PLANNER_MAX_TOKENS", "600"))


def load_preferences():
    pref_path = APP_DIR / "preferences.json"
    if pref_path.exists():
        return json.loads(pref_path.read_text())
    return {}


def build_prompt(tasks, events, preferences, extra_context=""):
    pref_line = (
        f"User preferences: timezone={preferences.get('timezone','?')}, "
        f"style={preferences.get('reply_style','concise')}. "
        f"Never send anything automatically — only draft.\n"
    )
    task_lines = "\n".join(
        f"- {t['title']}" + (f" (due {t['due_date']})" if t.get("due_date") else "")
        for t in tasks
    ) or "(none)"
    event_lines = "\n".join(
        f"- {e['start_time']}: {e['title']}" for e in events
    ) or "(none)"

    prompt = (
        f"{pref_line}\n"
        f"Open tasks:\n{task_lines}\n\n"
        f"Today's schedule:\n{event_lines}\n\n"
        f"{extra_context}\n"
        f"Write a short, practical draft plan for today. "
        f"For each suggestion, briefly note which task or event it's based on. "
        f"This is a DRAFT ONLY — do not claim anything has been sent, posted, or done."
    )
    return prompt


def _call_local(prompt):
    if not LOCAL_ENABLED:
        return None
    try:
        result = subprocess.run(
            [LLAMA_BIN, "-m", MODEL_PATH, "-p", prompt, "-n", "300"],
            capture_output=True, text=True, timeout=60,
        )
        output = result.stdout.strip()
        return output if output else None
    except Exception as e:
        print(f"[planner] local model failed: {e}")
        return None


def _call_openrouter(prompt):
    if not OPENROUTER_API_KEY:
        return None
    try:
        resp = requests.post(
            "https://openrouter.ai/api/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "model": OPENROUTER_MODEL,
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": MAX_TOKENS,
            },
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        content = data["choices"][0]["message"].get("content")
        return content
    except Exception as e:
        print(f"[planner] OpenRouter failed: {e}")
        return None


def generate_plan(tasks, events, extra_context=""):
    """
    Returns (draft_text, reasoning, evidence, source) or (None, ...) if
    both local and cloud fail (e.g. fully offline with no local model
    downloaded yet — caller should fall back to the old rule-based
    planner in that case, never silently produce nothing).
    """
    preferences = load_preferences()
    prompt = build_prompt(tasks, events, preferences, extra_context)

    draft = _call_local(prompt)
    source = "local (Qwen 0.5B / llama.cpp)"

    if not draft:
        draft = _call_openrouter(prompt)
        source = f"cloud ({OPENROUTER_MODEL} via OpenRouter)"

    if not draft:
        return None, None, None, None

    reasoning = f"Generated by {source} from your current open tasks and today's schedule."
    evidence = (
        f"Source: local tasks/schedule tables ({len(tasks)} open tasks, "
        f"{len(events)} events), preferences.json, single source of truth = this device's own data. "
        f"Model used: {source}."
    )
    return draft, reasoning, evidence, source
