#!/usr/bin/env python3
"""
scripts/render_scope_policy.py
==============================
Documentation-as-Code: render markdown tables from config/scope_policy.yaml.

Usage:
  python3 scripts/render_scope_policy.py
  python3 scripts/render_scope_policy.py --check
  python3 scripts/render_scope_policy.py -o path.md
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover
    print("PyYAML required: pip install PyYAML", file=sys.stderr)
    sys.exit(2)

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_POLICY = ROOT / "config" / "scope_policy.yaml"
DEFAULT_OUTPUT = ROOT / "docs" / "SCOPE_POLICY.md"

_GATE_NOTES = {
    "offensive": "Requires target allowlist in `config/scope.json` (exact host/IP or CIDR).",
    "deploy": "Requires `/scope arm-deploy` window (`deploy_armed_until` in scope.json).",
}


def load_policy(path: Path) -> dict[str, Any]:
    path = Path(path).resolve()
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(raw, dict):
        raise ValueError(f"invalid scope policy: {path}")

    defaults = raw.get("defaults") or {}
    if not isinstance(defaults, dict):
        defaults = {}

    messages = raw.get("messages") or {}
    if not isinstance(messages, dict):
        messages = {}

    offensive = [
        str(x).strip()
        for x in (raw.get("offensive_tools") or [])
        if str(x).strip()
    ]
    deploy = [
        str(x).strip()
        for x in (raw.get("deploy_tools") or [])
        if str(x).strip()
    ]

    return {
        "version": raw.get("version", 1),
        "defaults": defaults,
        "offensive_tools": sorted(set(offensive)),
        "deploy_tools": sorted(set(deploy)),
        "messages": {
            k: " ".join(str(v).split())
            for k, v in messages.items()
            if isinstance(v, str) and v.strip()
        },
        "source": path,
    }


def render_markdown(policy: dict[str, Any]) -> str:
    source = Path(policy["source"])
    try:
        source_label = str(source.resolve().relative_to(ROOT))
    except ValueError:
        source_label = str(source)

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    defaults = policy["defaults"]
    offensive = policy["offensive_tools"]
    deploy = policy["deploy_tools"]
    messages = policy["messages"]

    lines: list[str] = [
        "# KerrOS Scope Policy",
        "",
        f"> Generated from `{source_label}` by `scripts/render_scope_policy.py` "
        f"on **{generated}**.",
        ">",
        "> Do not edit this file by hand — re-run the renderer after changing "
        "`config/scope_policy.yaml`.",
        ">",
        "> Runtime allowlists (authorized targets/CIDRs and the deploy arm "
        "window) live in `config/scope.json` and are **not** listed here.",
        "",
        "## Summary",
        "",
        "| Class | Count | Gate |",
        "|-------|------:|------|",
        f"| offensive | {len(offensive)} | target allowlist (`scope.json`) |",
        f"| deploy | {len(deploy)} | armed deploy window |",
        f"| **total gated** | **{len(offensive) + len(deploy)}** | |",
        "",
        "## Defaults",
        "",
        "| Key | Value |",
        "|-----|-------|",
    ]

    for key in sorted(defaults):
        lines.append(f"| `{key}` | `{defaults[key]}` |")

    lines.extend(
        [
            "",
            f"Policy version: **{policy.get('version', 1)}**",
            "",
            "## Offensive tools",
            "",
            _GATE_NOTES["offensive"],
            "",
            "| Tool | Class |",
            "|------|-------|",
        ]
    )
    for tool in offensive:
        lines.append(f"| `{tool}` | offensive |")

    lines.extend(
        [
            "",
            "## Deploy tools",
            "",
            _GATE_NOTES["deploy"],
            "",
            "| Tool | Class |",
            "|------|-------|",
        ]
    )
    for tool in deploy:
        lines.append(f"| `{tool}` | deploy |")

    lines.extend(["", "## Deny messages", ""])
    if messages:
        for key in sorted(messages):
            lines.append(f"### `{key}`")
            lines.append("")
            lines.append(f"> {messages[key]}")
            lines.append("")
    else:
        lines.append("_(none defined)_")
        lines.append("")

    lines.extend(
        [
            "## How to regenerate",
            "",
            "```bash",
            "python3 scripts/render_scope_policy.py",
            "python3 scripts/render_scope_policy.py --check  # CI drift check",
            "```",
            "",
            "CLI: `/scope policy` (runtime summary) · `/scope policy export`",
            "",
        ]
    )
    return "\n".join(lines)


def _normalize_for_compare(text: str) -> str:
    out = []
    for line in text.splitlines():
        if line.startswith("> Generated from "):
            out.append("> Generated from scope policy by scripts/render_scope_policy.py.")
        else:
            out.append(line)
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-i",
        "--input",
        type=Path,
        default=DEFAULT_POLICY,
        help="Path to scope_policy.yaml",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Markdown output path (default: docs/SCOPE_POLICY.md)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if output is missing or stale (ignoring timestamp)",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print markdown to stdout instead of writing a file",
    )
    args = parser.parse_args(argv)

    policy = load_policy(args.input)
    markdown = render_markdown(policy)

    if args.stdout:
        sys.stdout.write(markdown)
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        if not args.output.exists():
            print(f"MISSING: {args.output}", file=sys.stderr)
            return 1
        existing = args.output.read_text(encoding="utf-8")
        if _normalize_for_compare(existing) != _normalize_for_compare(markdown):
            print(
                f"STALE: {args.output} — run scripts/render_scope_policy.py",
                file=sys.stderr,
            )
            return 1
        print(
            f"OK: {args.output} is up to date "
            f"({len(policy['offensive_tools'])} offensive, "
            f"{len(policy['deploy_tools'])} deploy)"
        )
        return 0

    args.output.write_text(markdown, encoding="utf-8")
    print(
        f"Wrote {args.output} "
        f"({len(policy['offensive_tools'])} offensive, "
        f"{len(policy['deploy_tools'])} deploy)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
