#!/usr/bin/env python3
"""
scripts/render_capabilities.py
================================
Documentation-as-Code: render markdown status tables from
config/capabilities/*.yaml manifests.

Usage:
  python3 scripts/render_capabilities.py
  python3 scripts/render_capabilities.py --check   # exit 1 if docs/CAPABILITIES.md is stale
  python3 scripts/render_capabilities.py -o path.md
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    print("PyYAML required: pip install PyYAML", file=sys.stderr)
    sys.exit(2)

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST_DIR = ROOT / "config" / "capabilities"
DEFAULT_OUTPUT = ROOT / "docs" / "CAPABILITIES.md"


def load_capabilities(manifest_dir: Path) -> list[dict]:
    caps: list[dict] = []
    manifest_dir = Path(manifest_dir).resolve()
    for path in sorted(manifest_dir.glob("*.yaml")):
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        entries = raw.get("capabilities", []) if isinstance(raw, dict) else []
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            name = str(entry.get("name", "")).strip()
            if not name:
                continue
            caps.append(
                {
                    "name": name,
                    "kind": str(entry.get("kind", "tool")).strip() or "tool",
                    "permissions": [str(x) for x in entry.get("permissions", [])],
                    "dependencies": [str(x) for x in entry.get("dependencies", [])],
                    "setup_required": bool(entry.get("setup_required", False)),
                    "setup_state": str(entry.get("setup_state", "unknown")),
                    "metadata": dict(entry.get("metadata", {}) or {}),
                    "source": path.name,
                }
            )
    caps.sort(key=lambda c: (c["kind"], c["name"]))
    return caps


def _cell(value: str, width: int = 60) -> str:
    text = " ".join(str(value).split())
    if len(text) > width:
        return text[: width - 1] + "…"
    return text


def render_markdown(caps: list[dict], *, manifest_dir: Path) -> str:
    by_kind: dict[str, list[dict]] = defaultdict(list)
    for cap in caps:
        by_kind[cap["kind"]].append(cap)

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    try:
        manifest_label = str(manifest_dir.resolve().relative_to(ROOT))
    except ValueError:
        manifest_label = str(manifest_dir)

    lines: list[str] = [
        "# KerrOS Capability Status",
        "",
        f"> Generated from `{manifest_label}/*.yaml` "
        f"by `scripts/render_capabilities.py` on **{generated}**.",
        ">",
        "> Do not edit this file by hand — re-run the renderer after "
        "changing manifests.",
        ">",
        "> Counts below are **manifest-only**. At boot the kernel also "
        "bootstraps claw tools from `tools.registry.TOOL_DEFINITIONS`, so "
        "`/capabilities` may show additional `tool:*` entries.",
        "",
        "## Summary",
        "",
        "| Kind | Count |",
        "|------|------:|",
    ]
    for kind in sorted(by_kind):
        lines.append(f"| {kind} | {len(by_kind[kind])} |")
    lines.append(f"| **total** | **{len(caps)}** |")
    lines.extend(["", "## Manifest sources", ""])
    sources = sorted({c["source"] for c in caps})
    for src in sources:
        count = sum(1 for c in caps if c["source"] == src)
        lines.append(f"- `{src}` — {count} capabilities")

    for kind in sorted(by_kind):
        lines.extend(
            [
                "",
                f"## {kind.title()} capabilities",
                "",
                "| Name | State | Permissions | Dependencies | Source | Notes |",
                "|------|-------|-------------|--------------|--------|-------|",
            ]
        )
        for cap in by_kind[kind]:
            notes = (
                cap["metadata"].get("notes")
                or cap["metadata"].get("role")
                or cap["metadata"].get("description")
                or ""
            )
            lines.append(
                "| {name} | {state} | {perms} | {deps} | `{source}` | {notes} |".format(
                    name=cap["name"],
                    state=cap["setup_state"],
                    perms=", ".join(cap["permissions"]) or "—",
                    deps=", ".join(cap["dependencies"]) or "—",
                    source=cap["source"],
                    notes=_cell(notes) or "—",
                )
            )

    lines.extend(
        [
            "",
            "## How to regenerate",
            "",
            "```bash",
            "python3 scripts/render_capabilities.py",
            "python3 scripts/render_capabilities.py --check  # CI drift check",
            "```",
            "",
            "CLI: `/capabilities` (runtime registry) · `/capabilities provider`",
            "",
        ]
    )
    return "\n".join(lines)


def _normalize_for_compare(text: str) -> str:
    """Drop the generated timestamp line so --check is stable across runs."""
    out = []
    for line in text.splitlines():
        if line.startswith("> Generated from "):
            out.append("> Generated from manifests by scripts/render_capabilities.py.")
        else:
            out.append(line)
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-d",
        "--manifest-dir",
        type=Path,
        default=DEFAULT_MANIFEST_DIR,
        help="Directory containing capability YAML manifests",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Markdown output path (default: docs/CAPABILITIES.md)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if output is missing or stale (ignoring timestamp)",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print markdown to stdout instead of writing a file",
    )
    args = parser.parse_args(argv)

    caps = load_capabilities(args.manifest_dir)
    markdown = render_markdown(caps, manifest_dir=args.manifest_dir)

    if args.stdout:
        sys.stdout.write(markdown)
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        if not args.output.exists():
            print(f"MISSING: {args.output}", file=sys.stderr)
            return 1
        existing = args.output.read_text(encoding="utf-8")
        if _normalize_for_compare(existing) != _normalize_for_compare(markdown):
            print(f"STALE: {args.output} — run scripts/render_capabilities.py", file=sys.stderr)
            return 1
        print(f"OK: {args.output} is up to date ({len(caps)} capabilities)")
        return 0

    args.output.write_text(markdown, encoding="utf-8")
    print(f"Wrote {args.output} ({len(caps)} capabilities)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
